# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-02 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
